=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 7.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43
=end

module CbrainClient
  VERSION = '7.0.0'
end
