=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 5.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module CbrainClient

  class Userfile
    # ID number of the file.
    attr_accessor :id

    # Name of the file that the Userfile represents
    attr_accessor :name

    # Number of bytes used to store the file.
    attr_accessor :size

    # ID of the owner of the file.
    attr_accessor :user_id

    # ID of the parent Userfile, if any exists, or null otherwise.
    attr_accessor :parent_id

    # Type of the file. This is important in determining what tools can be run on the file. The most generic file types, are the Single File, which represents one file, and the File Collection, which represents a directory full of files.
    attr_accessor :type

    # ID of the group that owns the file, which determines its visibility status.
    attr_accessor :group_id

    # ID of the Data Provider that is hosting the persistent copy of the file. It may exist in caches across the systems that make up CBRAIN, as copies of the file are made in order to run scientific programs on them on remote systems.
    attr_accessor :data_provider_id

    # Boolean variable that specifies whether members of the owner group have access to modify or overwrite the file.
    attr_accessor :group_writable

    # Number of files that the Userfiles represents. For Single Files, this is always 1.
    attr_accessor :num_files

    # Boolean variable that specifies whether this file is hidden or not in the user interface.
    attr_accessor :hidden

    # Boolean variable that specifies whether any user can modify the contents of the file.
    attr_accessor :immutable

    # Boolean variable that specifies whether the file is available, uncompressed, or has been archived.
    attr_accessor :archived

    # Description of the file.
    attr_accessor :description


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'size' => :'size',
        :'user_id' => :'user_id',
        :'parent_id' => :'parent_id',
        :'type' => :'type',
        :'group_id' => :'group_id',
        :'data_provider_id' => :'data_provider_id',
        :'group_writable' => :'group_writable',
        :'num_files' => :'num_files',
        :'hidden' => :'hidden',
        :'immutable' => :'immutable',
        :'archived' => :'archived',
        :'description' => :'description'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'Integer',
        :'name' => :'String',
        :'size' => :'Integer',
        :'user_id' => :'Integer',
        :'parent_id' => :'Integer',
        :'type' => :'String',
        :'group_id' => :'Integer',
        :'data_provider_id' => :'Integer',
        :'group_writable' => :'String',
        :'num_files' => :'Integer',
        :'hidden' => :'String',
        :'immutable' => :'String',
        :'archived' => :'String',
        :'description' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.has_key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.has_key?(:'parent_id')
        self.parent_id = attributes[:'parent_id']
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'group_id')
        self.group_id = attributes[:'group_id']
      end

      if attributes.has_key?(:'data_provider_id')
        self.data_provider_id = attributes[:'data_provider_id']
      end

      if attributes.has_key?(:'group_writable')
        self.group_writable = attributes[:'group_writable']
      end

      if attributes.has_key?(:'num_files')
        self.num_files = attributes[:'num_files']
      end

      if attributes.has_key?(:'hidden')
        self.hidden = attributes[:'hidden']
      end

      if attributes.has_key?(:'immutable')
        self.immutable = attributes[:'immutable']
      end

      if attributes.has_key?(:'archived')
        self.archived = attributes[:'archived']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          size == o.size &&
          user_id == o.user_id &&
          parent_id == o.parent_id &&
          type == o.type &&
          group_id == o.group_id &&
          data_provider_id == o.data_provider_id &&
          group_writable == o.group_writable &&
          num_files == o.num_files &&
          hidden == o.hidden &&
          immutable == o.immutable &&
          archived == o.archived &&
          description == o.description
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, name, size, user_id, parent_id, type, group_id, data_provider_id, group_writable, num_files, hidden, immutable, archived, description].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CbrainClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
