=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 5.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CbrainClient::DataProvidersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DataProvidersApi' do
  before do
    # run before each test
    @instance = CbrainClient::DataProvidersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DataProvidersApi' do
    it 'should create an instance of DataProvidersApi' do
      expect(@instance).to be_instance_of(CbrainClient::DataProvidersApi)
    end
  end

  # unit tests for data_providers_get
  # Get a list of the Data Providers available to the current user.
  # This method returns a list of Data Provider objects that represent servers with disk space accessible for storing Userfiles. 
  # @param [Hash] opts the optional parameters
  # @return [Array<DataProvider>]
  describe 'data_providers_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for data_providers_id_browse_get
  # List the files on a Data Provider.
  # This method allows the inspection of what files are present on a Data Provider specified by the ID parameter. Files that are not yet registered as Userfiles are visible using this method, as well as regularly accessible Userfiles. 
  # @param id The ID of the Data Provider to browse.
  # @param [Hash] opts the optional parameters
  # @return [Array<FileInfo>]
  describe 'data_providers_id_browse_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for data_providers_id_delete_post
  # Deletes unregistered files from a CBRAIN Data provider.
  # This method allows files that have not been registered from CBRAIN to be deleted. This may be necessary if files were uploaded in error, or if they were unregistered but not immediately deleted. 
  # @param id The ID of the Data Provider to delete files from.
  # @param multi_registration_mod_req Arrays containing the files to delete.
  # @param [Hash] opts the optional parameters
  # @return [RegistrationInfo]
  describe 'data_providers_id_delete_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for data_providers_id_get
  # Get information on a particular Data Provider.
  # This method returns a single Data Provider specified by the ID parameter 
  # @param id ID of the Data Provider to get information on.
  # @param [Hash] opts the optional parameters
  # @return [DataProvider]
  describe 'data_providers_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for data_providers_id_is_alive_get
  # Pings a Data Provider to check if it is running.
  # This method allows the querying of a Data Provider specified by the ID parameter to see if it is running or not. 
  # @param id The ID of the Data Provider to query.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'data_providers_id_is_alive_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for data_providers_id_register_post
  # Registers a file as a Userfile in CBRAIN.
  # This method allows new files to be added to CBRAIN. The files must first be transfered to the Data Provider via SFTP. For more information on SFTP file transfers, consult the CBRAIN Wiki documentation. Once files are present on the Data Provider, this method registers them in CBRAIN by specifying the file type. You can also specify to copy/move the files to another Data Provider after file registration. 
  # @param id The ID of the Data Provider to register files on.
  # @param multi_registration_mod_req Arrays containing the filenames and types to register.
  # @param [Hash] opts the optional parameters
  # @return [RegistrationInfo]
  describe 'data_providers_id_register_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for data_providers_id_unregister_post
  # Unregisters files as Userfile in CBRAIN.
  # This method allows files to be unregistered from CBRAIN. This will not delete the files, but removes them from the CBRAIN database, so Tools may no longer be run on them. 
  # @param id The ID of the Data Provider to unregister files from.
  # @param multi_registration_mod_req Arrays containing the filenames to unregister.
  # @param [Hash] opts the optional parameters
  # @return [RegistrationInfo]
  describe 'data_providers_id_unregister_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
