=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 5.1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for CbrainClient::SessionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SessionsApi' do
  before do
    # run before each test
    @instance = CbrainClient::SessionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SessionsApi' do
    it 'should create an instance of SessionsApi' do
      expect(@instance).to be_instance_of(CbrainClient::SessionsApi)
    end
  end

  # unit tests for session_delete
  # Destroy the current session
  # This destroys the current session, effectively terminating the access to the service. 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'session_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for session_get
  # Get session information
  # This returns information about the current session. 
  # @param [Hash] opts the optional parameters
  # @return [SessionInfo]
  describe 'session_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for session_post
  # Create a new session
  # This is the main entry point to create a CBRAIN session. Note that if a user is currently logged in, a new session will not be created, and the current session will be re-used. 
  # @param login The username of the user trying to connect.
  # @param password The password of the user
  # @param [Hash] opts the optional parameters
  # @return [SessionInfo]
  describe 'session_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
