=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 5.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for CbrainClient::TasksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TasksApi' do
  before do
    # run before each test
    @instance = CbrainClient::TasksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TasksApi' do
    it 'should create an instance of TasksApi' do
      expect(@instance).to be_instance_of(CbrainClient::TasksApi)
    end
  end

  # unit tests for tasks_get
  # Get the list of Tasks.
  # This method returns the list of Tasks accessible to the current user. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number when paginating. See also the per_page parameter
  # @option opts [Integer] :per_page Size of each page when paginating. See also the page parameter
  # @return [Array<CbrainTask>]
  describe 'tasks_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tasks_id_get
  # Get information on a Task.
  # This method returns information on a Task, including its status, Task restartability and information on where the results are kept. 
  # @param id The ID number of the Task to delete.
  # @param [Hash] opts the optional parameters
  # @return [CbrainTask]
  describe 'tasks_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tasks_post
  # Create a new Task.
  # This method allows the creation of a new Task. 
  # @param cbrain_task The task to create.
  # @param [Hash] opts the optional parameters
  # @return [Array<CbrainTask>]
  describe 'tasks_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
