=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 5.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for CbrainClient::ToolsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ToolsApi' do
  before do
    # run before each test
    @instance = CbrainClient::ToolsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ToolsApi' do
    it 'should create an instance of ToolsApi' do
      expect(@instance).to be_instance_of(CbrainClient::ToolsApi)
    end
  end

  # unit tests for tools_get
  # Get the list of Tools.
  # This method returns a list of all of the Tools that exist in CBRAIN. Tools encapsulate a scientific program designed to extract information from an input Userfile. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number when paginating. See also the per_page parameter
  # @option opts [Integer] :per_page Size of each page when paginating. See also the page parameter
  # @return [Array<Tool>]
  describe 'tools_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
