=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 5.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CbrainClient::ToolConfigsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ToolConfigsApi' do
  before do
    # run before each test
    @instance = CbrainClient::ToolConfigsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ToolConfigsApi' do
    it 'should create an instance of ToolConfigsApi' do
      expect(@instance).to be_instance_of(CbrainClient::ToolConfigsApi)
    end
  end

  # unit tests for tool_configs_get
  # Get a list of tool versions installed.
  # This method returns a list of tool config objects. 
  # @param [Hash] opts the optional parameters
  # @return [Array<ToolConfig>]
  describe 'tool_configs_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tool_configs_id_get
  # Get information about a particular tool configuration
  # Returns the information about how a particular configuration of a tool on an execution server. 
  # @param id the ID of the configuration
  # @param [Hash] opts the optional parameters
  # @return [ToolConfig]
  describe 'tool_configs_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
