=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 6.4.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CbrainClient::BatchTaskModReq
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BatchTaskModReq' do
  before do
    # run before each test
    @instance = CbrainClient::BatchTaskModReq.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BatchTaskModReq' do
    it 'should create an instance of BatchTaskModReq' do
      expect(@instance).to be_instance_of(CbrainClient::BatchTaskModReq)
    end
  end
  describe 'test attribute "tasklist"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "batch_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
