=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 5.1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CbrainClient::UserfileModReq
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserfileModReq' do
  before do
    # run before each test
    @instance = CbrainClient::UserfileModReq.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserfileModReq' do
    it 'should create an instance of UserfileModReq' do
      expect(@instance).to be_instance_of(CbrainClient::UserfileModReq)
    end
  end
  describe 'test attribute "userfile"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
