=begin
#CBRAIN API

#API for interacting with the CBRAIN Platform

OpenAPI spec version: 5.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'cbrain_client/api_client'
require 'cbrain_client/api_error'
require 'cbrain_client/version'
require 'cbrain_client/configuration'

# Models
require 'cbrain_client/models/bourreau'
require 'cbrain_client/models/cbrain_task'
require 'cbrain_client/models/cbrain_task_mod_req'
require 'cbrain_client/models/data_provider'
require 'cbrain_client/models/file_info'
require 'cbrain_client/models/group'
require 'cbrain_client/models/group_mod_req'
require 'cbrain_client/models/multi_registration_mod_req'
require 'cbrain_client/models/multi_userfiles_mod_req'
require 'cbrain_client/models/registration_info'
require 'cbrain_client/models/session_info'
require 'cbrain_client/models/tag'
require 'cbrain_client/models/tag_mod_req'
require 'cbrain_client/models/tool'
require 'cbrain_client/models/tool_config'
require 'cbrain_client/models/user'
require 'cbrain_client/models/user_mod_req'
require 'cbrain_client/models/userfile'
require 'cbrain_client/models/userfile_mod_req'

# APIs
require 'cbrain_client/api/bourreaux_api'
require 'cbrain_client/api/data_providers_api'
require 'cbrain_client/api/groups_api'
require 'cbrain_client/api/sessions_api'
require 'cbrain_client/api/tags_api'
require 'cbrain_client/api/tasks_api'
require 'cbrain_client/api/tool_configs_api'
require 'cbrain_client/api/tools_api'
require 'cbrain_client/api/userfiles_api'
require 'cbrain_client/api/users_api'

module CbrainClient
  class << self
    # Customize default settings for the SDK using block.
    #   CbrainClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
